version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: post_analyzer_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: post_analyzer
      MYSQL_USER: post_analyzer
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - post_analyzer_network

  # C++ Analysis Service
  cpp-analyzer:
    build:
      context: ./backend/cpp
      dockerfile: Dockerfile
    container_name: post_analyzer_cpp
    ports:
      - "8000:8000"
    networks:
      - post_analyzer_network
    depends_on:
      - mysql

  # Node.js Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: post_analyzer_backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=post_analyzer
      - DB_USER=post_analyzer
      - DB_PASSWORD=password
      - API_KEY=your-secret-api-key-here
      - FRONTEND_URL=http://localhost:3000
      - CPP_SERVICE_URL=http://cpp-analyzer:8000
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - cpp-analyzer
    networks:
      - post_analyzer_network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: post_analyzer_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_API_KEY=your-secret-api-key-here
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - post_analyzer_network

volumes:
  mysql_data:

networks:
  post_analyzer_network:
    driver: bridge 